In [25]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn import tree
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [3]:
df = pd.read_excel('iris.xls')
data = df.copy()

In [6]:
df.head()

SL   SW   PL   PW Classification
0  5.1  3.5  1.4  0.2    Iris-setosa
1  4.9  3.0  1.4  0.2    Iris-setosa
2  NaN  3.2  1.3  0.2    Iris-setosa
3  4.6  3.1  1.5  0.2    Iris-setosa
4  5.0  3.6  1.4  0.2    Iris-setosa

In [7]:
df.isnull().values.any()

True

In [8]:
df.isnull().sum()

SL                7
SW                6
PL                6
PW                0
Classification    0
dtype: int64

In [ ]:
df.shape

In [ ]:
df.info()

In [ ]:
df.describe()

In [5]:
# filling missing values using mean

for i in ['SL','SW','PL']:
    data[i] = data[i].fillna(data[i].mean())
data.isna().sum()

SL                0
SW                0
PL                0
PW                0
Classification    0
dtype: int64

In [9]:
data.head()

SL   SW   PL   PW Classification
0  5.100000  3.5  1.4  0.2    Iris-setosa
1  4.900000  3.0  1.4  0.2    Iris-setosa
2  5.855944  3.2  1.3  0.2    Iris-setosa
3  4.600000  3.1  1.5  0.2    Iris-setosa
4  5.000000  3.6  1.4  0.2    Iris-setosa

In [10]:
data.Classification.unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [11]:
d = {'Iris-setosa': 1, 'Iris-versicolor': 2, 'Iris-virginica': 3}
data['Classification'] = data['Classification'].map(d)

In [12]:
data.head()

SL   SW   PL   PW  Classification
0  5.100000  3.5  1.4  0.2               1
1  4.900000  3.0  1.4  0.2               1
2  5.855944  3.2  1.3  0.2               1
3  4.600000  3.1  1.5  0.2               1
4  5.000000  3.6  1.4  0.2               1

In [14]:
iris_features = data.columns.tolist()
iris_features.remove('Classification') 

In [16]:
# copying features to X
X = data[iris_features].copy()
X.columns

Index(['SL', 'SW', 'PL', 'PW'], dtype='object')

In [38]:
# copying target to Y
y = data[['Classification']].copy()
y

Classification
0                 1
1                 1
2                 1
3                 1
4                 1
..              ...
145               3
146               3
147               3
148               3
149               3

[150 rows x 1 columns]

In [34]:
X_train, X_test, y_train, y_test = train_test_split(X,y,random_state=40,test_size=.35)

In [29]:
iris_classifier = tree.DecisionTreeClassifier(max_leaf_nodes=len(X.columns), random_state=0)
iris_classifier.fit(X_train, y_train)

DecisionTreeClassifier(max_leaf_nodes=4, random_state=0)

In [30]:
# Creating prediction
predictions = iris_classifier.predict(X_test)

In [31]:
# Measuring accuracy of the classifier
accuracy_score(y_true = y_test, y_pred = predictions)

1.0

In [32]:
predictions

array([3, 1, 3, 1, 3, 3, 1, 1, 3, 1, 1, 3, 1, 1, 3], dtype=int64)

In [33]:
confusion_matrix(y_true = y_test, y_pred = predictions)

array([[8, 0],
       [0, 7]], dtype=int64)

## LOGISTIC REGERESSION MODEL

In [48]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

log_model=LogisticRegression(solver='newton-cg')
log_model.fit(X_train,y_train.values.ravel())
prediction=log_model.predict(X_test)
print("F1_score :",f1_score(y_test,prediction,average='micro'))
print("Accuracy score :",accuracy_score(y_test,prediction))
print("Confusion_matrix :",confusion_matrix(y_test,prediction))

F1_score : 0.9622641509433962
Accuracy score : 0.9622641509433962
Confusion_matrix : [[16  2  0]
 [ 0 17  0]
 [ 0  0 18]]


## RANDOM FOREST CLASSIFIER

In [42]:
from sklearn.ensemble import RandomForestClassifier
rf_mod = RandomForestClassifier(random_state=40)
rf_mod.fit(X_train,y_train.values.ravel())
y_pred=rf_mod.predict(X_test)
print('Accuracy Score:',accuracy_score(y_test,y_pred))
print('Conclusion matrix\n',confusion_matrix(y_test,y_pred))

Accuracy Score: 0.9811320754716981
Conclusion matrix
 [[18  0  0]
 [ 0 17  0]
 [ 0  1 17]]


## SVM MODEL

In [39]:
from sklearn.svm import SVC
svm_gauss=SVC(kernel='rbf')
svm_gauss.fit(X_train,y_train.values.ravel())
y_pred=svm_gauss.predict(X_test)

In [40]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print('Accuracy Score:',accuracy_score(y_test,y_pred))
print('Conclusion matrix\n',confusion_matrix(y_test,y_pred))

Accuracy Score: 0.9622641509433962
Conclusion matrix
 [[16  2  0]
 [ 0 17  0]
 [ 0  0 18]]
